// source: another_interval.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require("google-protobuf");
var goog = jspb;
var global = function () {
  if (this) {
    return this;
  }
  if (typeof window !== "undefined") {
    return window;
  }
  if (typeof global !== "undefined") {
    return global;
  }
  if (typeof self !== "undefined") {
    return self;
  }
  return Function("return this")();
}.call(null);

var validate_validate_pb = require("./validate/validate_pb.js.js");
goog.object.extend(proto, validate_validate_pb);
goog.exportSymbol("proto.pb.AnotherIntervalRequest", null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.AnotherIntervalRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.AnotherIntervalRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.AnotherIntervalRequest.displayName =
    "proto.pb.AnotherIntervalRequest";
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.pb.AnotherIntervalRequest.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.pb.AnotherIntervalRequest.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.pb.AnotherIntervalRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.pb.AnotherIntervalRequest.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        reqInterval: jspb.Message.getFieldWithDefault(msg, 1, ""),
        identifier: jspb.Message.getFieldWithDefault(msg, 2, ""),
        mode: jspb.Message.getFieldWithDefault(msg, 3, ""),
        stage: jspb.Message.getFieldWithDefault(msg, 4, 0),
        userId: jspb.Message.getFieldWithDefault(msg, 5, ""),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.AnotherIntervalRequest}
 */
proto.pb.AnotherIntervalRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.AnotherIntervalRequest();
  return proto.pb.AnotherIntervalRequest.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.AnotherIntervalRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.AnotherIntervalRequest}
 */
proto.pb.AnotherIntervalRequest.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setReqInterval(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setIdentifier(value);
        break;
      case 3:
        var value = /** @type {string} */ (reader.readString());
        msg.setMode(value);
        break;
      case 4:
        var value = /** @type {number} */ (reader.readInt32());
        msg.setStage(value);
        break;
      case 5:
        var value = /** @type {string} */ (reader.readString());
        msg.setUserId(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.AnotherIntervalRequest.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.pb.AnotherIntervalRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.AnotherIntervalRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.AnotherIntervalRequest.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = message.getReqInterval();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getIdentifier();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
  f = message.getMode();
  if (f.length > 0) {
    writer.writeString(3, f);
  }
  f = message.getStage();
  if (f !== 0) {
    writer.writeInt32(4, f);
  }
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(5, f);
  }
};

/**
 * optional string req_interval = 1;
 * @return {string}
 */
proto.pb.AnotherIntervalRequest.prototype.getReqInterval = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

/**
 * @param {string} value
 * @return {!proto.pb.AnotherIntervalRequest} returns this
 */
proto.pb.AnotherIntervalRequest.prototype.setReqInterval = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string identifier = 2;
 * @return {string}
 */
proto.pb.AnotherIntervalRequest.prototype.getIdentifier = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};

/**
 * @param {string} value
 * @return {!proto.pb.AnotherIntervalRequest} returns this
 */
proto.pb.AnotherIntervalRequest.prototype.setIdentifier = function (value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * optional string mode = 3;
 * @return {string}
 */
proto.pb.AnotherIntervalRequest.prototype.getMode = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};

/**
 * @param {string} value
 * @return {!proto.pb.AnotherIntervalRequest} returns this
 */
proto.pb.AnotherIntervalRequest.prototype.setMode = function (value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};

/**
 * optional int32 stage = 4;
 * @return {number}
 */
proto.pb.AnotherIntervalRequest.prototype.getStage = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};

/**
 * @param {number} value
 * @return {!proto.pb.AnotherIntervalRequest} returns this
 */
proto.pb.AnotherIntervalRequest.prototype.setStage = function (value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};

/**
 * optional string user_id = 5;
 * @return {string}
 */
proto.pb.AnotherIntervalRequest.prototype.getUserId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};

/**
 * @param {string} value
 * @return {!proto.pb.AnotherIntervalRequest} returns this
 */
proto.pb.AnotherIntervalRequest.prototype.setUserId = function (value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};

goog.object.extend(exports, proto.pb);
