/**
 * @fileoverview gRPC-Web generated client stub for pb
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.19.1
// source: service_bitmoi.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var candles_pb = require('./candles_pb.js')

var score_pb = require('./score_pb.js')

var another_interval_pb = require('./another_interval_pb.js')

var google_api_annotations_pb = require('./google/api/annotations_pb.js')
const proto = {};
proto.pb = require('./service_bitmoi_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.pb.BitmoiClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.pb.BitmoiPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pb.CandlesRequest,
 *   !proto.pb.CandlesResponse>}
 */
const methodDescriptor_Bitmoi_RequestCandles = new grpc.web.MethodDescriptor(
  '/pb.Bitmoi/RequestCandles',
  grpc.web.MethodType.UNARY,
  candles_pb.CandlesRequest,
  candles_pb.CandlesResponse,
  /**
   * @param {!proto.pb.CandlesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  candles_pb.CandlesResponse.deserializeBinary
);


/**
 * @param {!proto.pb.CandlesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pb.CandlesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pb.CandlesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pb.BitmoiClient.prototype.requestCandles =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pb.Bitmoi/RequestCandles',
      request,
      metadata || {},
      methodDescriptor_Bitmoi_RequestCandles,
      callback);
};


/**
 * @param {!proto.pb.CandlesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pb.CandlesResponse>}
 *     Promise that resolves to the response
 */
proto.pb.BitmoiPromiseClient.prototype.requestCandles =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pb.Bitmoi/RequestCandles',
      request,
      metadata || {},
      methodDescriptor_Bitmoi_RequestCandles);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pb.ScoreRequest,
 *   !proto.pb.ScoreResponse>}
 */
const methodDescriptor_Bitmoi_PostScore = new grpc.web.MethodDescriptor(
  '/pb.Bitmoi/PostScore',
  grpc.web.MethodType.UNARY,
  score_pb.ScoreRequest,
  score_pb.ScoreResponse,
  /**
   * @param {!proto.pb.ScoreRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  score_pb.ScoreResponse.deserializeBinary
);


/**
 * @param {!proto.pb.ScoreRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pb.ScoreResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pb.ScoreResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pb.BitmoiClient.prototype.postScore =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pb.Bitmoi/PostScore',
      request,
      metadata || {},
      methodDescriptor_Bitmoi_PostScore,
      callback);
};


/**
 * @param {!proto.pb.ScoreRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pb.ScoreResponse>}
 *     Promise that resolves to the response
 */
proto.pb.BitmoiPromiseClient.prototype.postScore =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pb.Bitmoi/PostScore',
      request,
      metadata || {},
      methodDescriptor_Bitmoi_PostScore);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pb.AnotherIntervalRequest,
 *   !proto.pb.CandlesResponse>}
 */
const methodDescriptor_Bitmoi_AnotherInterval = new grpc.web.MethodDescriptor(
  '/pb.Bitmoi/AnotherInterval',
  grpc.web.MethodType.UNARY,
  another_interval_pb.AnotherIntervalRequest,
  candles_pb.CandlesResponse,
  /**
   * @param {!proto.pb.AnotherIntervalRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  candles_pb.CandlesResponse.deserializeBinary
);


/**
 * @param {!proto.pb.AnotherIntervalRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pb.CandlesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pb.CandlesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pb.BitmoiClient.prototype.anotherInterval =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pb.Bitmoi/AnotherInterval',
      request,
      metadata || {},
      methodDescriptor_Bitmoi_AnotherInterval,
      callback);
};


/**
 * @param {!proto.pb.AnotherIntervalRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pb.CandlesResponse>}
 *     Promise that resolves to the response
 */
proto.pb.BitmoiPromiseClient.prototype.anotherInterval =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pb.Bitmoi/AnotherInterval',
      request,
      metadata || {},
      methodDescriptor_Bitmoi_AnotherInterval);
};


module.exports = proto.pb;

