name: Build react app

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve and create SSL files
        run: |
          cd frontend/server
          echo "${{ secrets.server_crt }}" > server.crt
          echo "${{ secrets.server_key }}" > server.key

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::071353287696:role/bitmoi-github-action
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: build react app
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: bitmoi-client
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd frontend
          npm install
          CI=false npm run build
          cd server
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push -a $ECR_REGISTRY/$ECR_REPOSITORY

#       - name: Restart server
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USERNAME }}
#           key: ${{ secrets.EC2_PRIV }}
#           script: |
#             cd /home/${{ secrets.EC2_USERNAME }}
#             ./stop.sh
#             ./login.sh
#             ./start.sh
